"""Meaningful codes, rich project configuration, and the BRD generator."""
from tests.conftest import auth


def test_customer_code_autogenerated(client, make_user):
    h = auth(make_user(role='manager')['token'])
    c = client.post('/api/customers', headers=h, json={'company_name': 'MPIA Services (PTY) Ltd'}).get_json()
    assert c['customer_code'] == 'MPIA'        # derived from the name, not a UUID
    # a second client whose name yields the same base gets a unique suffix
    c2 = client.post('/api/customers', headers=h, json={'company_name': 'MPIA Holdings'}).get_json()
    assert c2['customer_code'] == 'MPIA2'


def test_project_code_per_client_sequence(client, make_user):
    h = auth(make_user(role='manager')['token'])
    cust = client.post('/api/customers', headers=h, json={'company_name': 'Acme Corp'}).get_json()
    assert cust['customer_code'] == 'ACME'
    p1 = client.post('/api/projects', headers=h, json={'name': 'Platform', 'customer_id': cust['id']}).get_json()
    p2 = client.post('/api/projects', headers=h, json={'name': 'Mobile app', 'customer_id': cust['id']}).get_json()
    assert p1['project_code'] == 'ACME-001'
    assert p2['project_code'] == 'ACME-002'


def test_rich_project_config_persists(client, make_user):
    h = auth(make_user(role='manager')['token'])
    cust = client.post('/api/customers', headers=h, json={'company_name': 'Globex'}).get_json()
    p = client.post('/api/projects', headers=h, json={
        'name': 'AI Platform', 'customer_id': cust['id'],
        'project_type': 'AI & Automation', 'tech_stack': ['Python', 'FastAPI', 'OpenAI'],
        'estimated_cost': 120000, 'estimated_hours': 240, 'start_date': '2026-07-01',
        'scope': 'Build an AI assistant.', 'repository_url': 'https://github.com/x/y',
        'contract_value': 150000}).get_json()
    assert p['project_type'] == 'AI & Automation'
    assert p['tech_stack'] == ['Python', 'FastAPI', 'OpenAI']   # list round-trips
    assert p['estimated_cost'] == 120000
    assert p['start_date'] == '2026-07-01'                       # date string parsed
    assert p['repository_url'] == 'https://github.com/x/y'

    # update merges typed fields + dates cleanly
    upd = client.put(f"/api/projects/{p['id']}", headers=h, json={'estimated_hours': 300, 'tech_stack': ['Python', 'Django']}).get_json()
    assert upd['estimated_hours'] == 300 and upd['tech_stack'] == ['Python', 'Django']


def test_brd_pdf(client, make_user):
    h = auth(make_user(role='manager')['token'])
    cust = client.post('/api/customers', headers=h, json={'company_name': 'MPIA Services'}).get_json()
    p = client.post('/api/projects', headers=h, json={
        'name': 'ILMS', 'customer_id': cust['id'], 'system_name': 'Inspection Lifecycle Management System',
        'project_type': 'Custom Software', 'tech_stack': ['Flutter', 'Flask'], 'scope': 'Phase-based build.',
        'estimated_cost': 19000}).get_json()
    client.post(f"/api/projects/{p['id']}/phases", headers=h, json={'number': 1, 'total_phases': 3, 'title': 'Foundation'})
    client.post(f"/api/projects/{p['id']}/milestones", headers=h, json={'name': 'Deposit', 'amount': 3600})
    r = client.get(f"/api/projects/{p['id']}/brd.pdf", headers=h)
    assert r.status_code == 200
    assert r.content_type.startswith('application/pdf')
    assert r.data[:4] == b'%PDF'
