"""project showcase flag

Revision ID: 441c4240ce39
Revises: c655e3938f39
Create Date: 2026-06-03 15:58:00.785471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # commonly referenced by autogenerated JSONB(astext_type=Text())


# revision identifiers, used by Alembic.
revision: str = '441c4240ce39'
down_revision: Union[str, Sequence[str], None] = 'c655e3938f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('showcase', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'showcase')
    # ### end Alembic commands ###
