"""document engine: issuer, contract, milestone schedule, phases, project documents

Revision ID: 8837459b1a93
Revises: b7be0df5a007
Create Date: 2026-06-03 14:51:24.614414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # commonly referenced by autogenerated JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8837459b1a93'
down_revision: Union[str, Sequence[str], None] = 'b7be0df5a007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(length=10), nullable=False),
    sa.Column('doc_ref', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_ref')
    )
    op.create_table('project_phases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('total_phases', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('phase_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gate_criteria', sa.Text(), nullable=True),
    sa.Column('gate_status', sa.String(length=120), nullable=True),
    sa.Column('additional_scope', sa.Text(), nullable=True),
    sa.Column('triggers_invoice_ref', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_deliverables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('implementation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['project_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company_settings', sa.Column('legal_name', sa.String(length=250), nullable=True))
    op.add_column('company_settings', sa.Column('registration_number', sa.String(length=60), nullable=True))
    op.add_column('company_settings', sa.Column('signatory_name', sa.String(length=150), nullable=True))
    op.add_column('company_settings', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('company_settings', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('company_settings', sa.Column('vat_registered', sa.Boolean(), nullable=False))
    op.add_column('company_settings', sa.Column('vat_number', sa.String(length=60), nullable=True))
    op.add_column('company_settings', sa.Column('doc_ref_prefix', sa.String(length=10), nullable=True))
    op.add_column('company_settings', sa.Column('bank_name', sa.String(length=120), nullable=True))
    op.add_column('company_settings', sa.Column('bank_account_name', sa.String(length=150), nullable=True))
    op.add_column('company_settings', sa.Column('bank_account_number', sa.String(length=40), nullable=True))
    op.add_column('company_settings', sa.Column('bank_branch_code', sa.String(length=20), nullable=True))
    op.add_column('company_settings', sa.Column('bank_account_type', sa.String(length=40), nullable=True))
    op.add_column('company_settings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('milestones', sa.Column('sequence', sa.Integer(), nullable=True))
    op.add_column('milestones', sa.Column('trigger', sa.Text(), nullable=True))
    op.add_column('milestones', sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('milestones', sa.Column('invoice_ref', sa.String(length=50), nullable=True))
    op.add_column('milestones', sa.Column('payment_status', sa.String(length=30), nullable=True))
    op.add_column('projects', sa.Column('system_name', sa.String(length=250), nullable=True))
    op.add_column('projects', sa.Column('contract_ref', sa.String(length=80), nullable=True))
    op.add_column('projects', sa.Column('contract_signed_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'contract_value')
    op.drop_column('projects', 'contract_signed_date')
    op.drop_column('projects', 'contract_ref')
    op.drop_column('projects', 'system_name')
    op.drop_column('milestones', 'payment_status')
    op.drop_column('milestones', 'invoice_ref')
    op.drop_column('milestones', 'amount')
    op.drop_column('milestones', 'trigger')
    op.drop_column('milestones', 'sequence')
    op.drop_column('company_settings', 'updated_at')
    op.drop_column('company_settings', 'bank_account_type')
    op.drop_column('company_settings', 'bank_branch_code')
    op.drop_column('company_settings', 'bank_account_number')
    op.drop_column('company_settings', 'bank_account_name')
    op.drop_column('company_settings', 'bank_name')
    op.drop_column('company_settings', 'doc_ref_prefix')
    op.drop_column('company_settings', 'vat_number')
    op.drop_column('company_settings', 'vat_registered')
    op.drop_column('company_settings', 'website')
    op.drop_column('company_settings', 'address')
    op.drop_column('company_settings', 'signatory_name')
    op.drop_column('company_settings', 'registration_number')
    op.drop_column('company_settings', 'legal_name')
    op.drop_table('phase_deliverables')
    op.drop_table('project_phases')
    op.drop_table('project_documents')
    # ### end Alembic commands ###
