"""link tickets to project + SLA due date

Revision ID: ab78d9cd702b
Revises: d5ab3195989a
Create Date: 2026-06-03 15:35:08.389664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # commonly referenced by autogenerated JSONB(astext_type=Text())


# revision identifiers, used by Alembic.
revision: str = 'ab78d9cd702b'
down_revision: Union[str, Sequence[str], None] = 'd5ab3195989a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('tickets', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'due_date')
    op.drop_column('tickets', 'project_id')
    # ### end Alembic commands ###
