"""activity log: scope to project + client

Revision ID: c655e3938f39
Revises: ab78d9cd702b
Create Date: 2026-06-03 15:44:47.058914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # commonly referenced by autogenerated JSONB(astext_type=Text())


# revision identifiers, used by Alembic.
revision: str = 'c655e3938f39'
down_revision: Union[str, Sequence[str], None] = 'ab78d9cd702b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('activity_logs', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.add_column('activity_logs', sa.Column('summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'activity_logs', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column('activity_logs', 'summary')
    op.drop_column('activity_logs', 'customer_id')
    op.drop_column('activity_logs', 'project_id')
    # ### end Alembic commands ###
