"""company settings: tax (income tax reference) number

Revision ID: d3e8f1a47c20
Revises: 441c4240ce39
Create Date: 2026-06-04 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # commonly referenced by autogenerated JSONB(astext_type=Text())


# revision identifiers, used by Alembic.
revision: str = 'd3e8f1a47c20'
down_revision: Union[str, Sequence[str], None] = '441c4240ce39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nullable — applies cleanly over the existing company_settings row.
    op.add_column('company_settings', sa.Column('tax_number', sa.String(length=60), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('company_settings', 'tax_number')
