"""project configuration: type, tech stack, scope, estimates, urls, readme

Revision ID: d5ab3195989a
Revises: 8837459b1a93
Create Date: 2026-06-03 15:15:29.046734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # commonly referenced by autogenerated JSONB(astext_type=Text())


# revision identifiers, used by Alembic.
revision: str = 'd5ab3195989a'
down_revision: Union[str, Sequence[str], None] = '8837459b1a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_type', sa.String(length=60), nullable=True))
    op.add_column('projects', sa.Column('tech_stack', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('scope', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('estimated_cost', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('projects', sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('repository_url', sa.String(length=300), nullable=True))
    op.add_column('projects', sa.Column('live_url', sa.String(length=300), nullable=True))
    op.add_column('projects', sa.Column('readme', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'readme')
    op.drop_column('projects', 'live_url')
    op.drop_column('projects', 'repository_url')
    op.drop_column('projects', 'estimated_hours')
    op.drop_column('projects', 'estimated_cost')
    op.drop_column('projects', 'scope')
    op.drop_column('projects', 'tech_stack')
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###
